### PR TITLE
Update README to include Bower install and fix rm command typo

### PR DESCRIPTION
**Pull request by nelsyeung**
Correct me if I'm wrong but I believe the rm command should be rm myrefuge/db.sqlite3
I've also updated it to include the bower install, as this is also mandatory to get the project going.

### CODE REVIEW

**Comment by cazgp** [comment]
Ah... no not anymore. Bower is now controlled by Django. There's a setting in settings/common.py BOWER_APPS or something. Add your apps to that and run ./manage.py bower install. I will add that to the README. That command is already in the fabfile.

**Comment by nelsyeung** [comment]
My pull request basically include the ./manage.py bower install. Oh does that mean that the rm command should be removed from the README? it's rather confusing atm.

**Comment by cazgp** [comment]
Oh sorry! `fab install` includes `bower install`.

**Comment by nelsyeung** [comment]
Wait, but mine didn't work?! I had to run ./manage.py bower install in order to start working. If I just run fab install I won't have the components directory.

**Comment by cazgp** [comment]
Ah-ha. That's because there was a syntax error in the file. I've now fixed and pushed to master (yes, naughty...) Should all work now.

**Pull request closed without merging**
